name: CICD Workflow Build

on:
  push:
    branches:
      - main
  pull_request:
    types: closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ganti dengan versi Node.js yang sesuai

      - name: Install Node.js dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Sync staging to production
        run: |
          git push origin -d production
          git checkout -b production
          git merge production
          git push origin production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd public_html/junior_eduall/github/junior
            git pull origin production
          timeout: 120  # Increase timeout to 2 minutes
          retry: 3

